language: node_js

node_js:
  - node
env:
  - APPLICATION_TEST=true

notifications:
  slack: mifort:1WM7cdHbyutWvwq839SVnpQV

services:
  - mongodb

before_install:
  - sleep 15
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - chmod +x run_tests
  - chmod +x nightwatch
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - ./run_tests
